from pydantic import BaseModel, Field
from langchain_core.prompts import PromptTemplate
from core.llm_engine import get_llm

class OracleAudit(BaseModel):
    oracle_decision: str = Field(..., description="AUTHORIZE, ESCALATE, or REJECT")
    sla_risk_score: float = Field(..., description="0.0 - 100.0")
    audit_reasoning: str = Field(..., description="A highly technical, 2-sentence justification focusing on code safety, VRAM memory limits, or supply chain routing logic.")
    gitops_merge_flag: bool = Field(..., description="Boolean for authorization granted")

def audit_scout_report(scout_report: str) -> OracleAudit:
    """
    Compliance & Security Oracle.
    Audits Pull Requests generated by The Drafter before they are deployed.
    """
    llm = get_llm(temperature=0.0)
    structured_llm = llm.with_structured_output(OracleAudit)
    
    prompt = PromptTemplate(
        input_variables=["report"],
        template=(
            "[SYSTEM]\n"
            "You are the Compliance & Security Oracle. You are the final technical gatekeeper in the ChainReflex-OS GitOps pipeline.\n"
            "Your sole purpose is to audit the Pull Requests generated by The Drafter before they are deployed to production.\n\n"
            "[AUDIT DIRECTIVE]\n"
            "You must evaluate the Drafter's code patch against two strict heuristic criteria:\n"
            "1. System Continuity (SLA): Will merging this patch cause more downtime than the actual threat itself? (e.g., Does it unnecessarily sever a massive database connection to fix a minor log leak?)\n"
            "2. Regression Risk: Does the patch use unauthorized external libraries or introduce new, unvetted attack vectors?\n\n"
            "[DECISION MATRIX]\n"
            "- AUTHORIZE: The patch is idempotent, hardware-optimized (ROCm/C++), and technically safe to merge.\n"
            "- ESCALATE: The patch touches mission-critical routing logic with high uncertainty. Requires manual SOC review.\n"
            "- REJECT: The patch introduces a breaking change or regression.\n\n"
            "Drafter's PR / Report:\n{report}\n\n"
            "You must output your final audit in strict JSON matching the schema."
        )
    )
    
    chain = prompt | structured_llm
    
    try:
        result = chain.invoke({
            "report": scout_report
        })
        return result
    except Exception as e:
        # Fallback in case of error
        return OracleAudit(
            oracle_decision="REJECT",
            sla_risk_score=100.0,
            audit_reasoning=f"Error running Oracle audit: {str(e)}. Defaulting to REJECT for safety.",
            gitops_merge_flag=False
        )
